### ISSUE TITLE
Can't link external Jars with .class file when running the C++ wrapper jar

### ISSUE THREAD

**Issue by kenantufekci** [wshackle/java4cpp#1]
I am trying to run a class file through your C++ wrapper but I am running into issues when I try to use external jar files. I have a .java file that uses external jars to call other classes and I must include those jars in the classpath when compiling. However when I run your : 

java -jar target/java4cpp-1.0-SNAPSHOT-jar-with-dependencies.jar NexusTester 

I get:

Exception in thread "main" java.lang.NoClassDefFoundError 

I have tried everything but this was my last command:

java -cp .:jssc.jar:nexus.jar -jar /target/java4cpp-1.0-SNAPSHOT-jar-with-dependencies.jar -j jssc.jar -j nexus.jar -c NexusTester

It does not find the classes in the external jars. How do I link the external jars when running your C++ wrapper jar file at the same time with my class that requires external jars?

**Comment by wshackle** [comment]
Can you post the full text of the exception or preferably the full text of the output with the `-v` option?

I suspect the issue is that NexusTester is a class in one of those jars rather than a separate .class file.

The command as stated would require a file NexusTester.class to be in the current directory. 

To reduce the chances of this happening in the future, I have committed and pushed a change to prevent looking for a .class file in the current directory if the class could be found in the jar.

Note after pulling and recompiling the name of the jar will change to a version number of 1.2 ie
java4cpp-1.2-SNAPSHOT-jar-with-dependencies.jar

**Comment by wshackle** [comment]
I don't think you need the -j options unless you want wrappers for all the classes in the jars.

java -cp .:jssc.jar:nexus.jar -jar /target/java4cpp-1.0-SNAPSHOT-jar-with-dependencies.jar  -c NexusTester

This command expects there to be a file 

NexusTester.class 

in the current directory.

**Comment by kenantufekci** [comment]
My main class is NexusTester and it uses nexus.jar and jssc.jar as external jars

java -cp .:jssc.jar:nexus.jar -jar /home/pi/Desktop/java4cpp/target/java4cpp-1.0-SNAPSHOT-jar-with-dependencies.jar -j nexus.jar -j jssc.jar -c NexusTester -v

args = [-j, nexus.jar, -j, jssc.jar, -c, NexusTester, -v]
jar = nexus.jar
classStrings = [NexusTester]
classnamesToFind = [NexusTester]
namespace = JavaForCpp
output = JavaForCpp.cpp
header = JavaForCpp.h
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$1.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$10.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$11.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$12.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$13.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$14.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$15.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$16.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$17.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$18.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$19.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$2.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$3.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$4.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$5.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$6.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$7.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$8.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$9.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument$RunnableObservable.class
entryName = mdt/neuro/nexus/ThreadedNexusInstrument.class
skipping className=mdt.neuro.nexus.ThreadedNexusInstrument because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/ConnectionStatus.class
skipping className=mdt.neuro.nexus.ConnectionStatus because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/ThreadManager.class
skipping className=mdt.neuro.nexus.ThreadManager because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/SerialPortErrors.class
skipping className=mdt.neuro.nexus.SerialPortErrors because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/ParameterizedRunnable.class
skipping className=mdt.neuro.nexus.ParameterizedRunnable because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/ApplicationCommand.class
skipping className=mdt.neuro.nexus.ApplicationCommand because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/ObservableConnection$1.class
entryName = mdt/neuro/nexus/ObservableConnection.class
skipping className=mdt.neuro.nexus.ObservableConnection because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/NexusInstrument$TemplateSubtractor.class
entryName = mdt/neuro/nexus/NexusInstrument.class
skipping className=mdt.neuro.nexus.NexusInstrument because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/Util.class
skipping className=mdt.neuro.nexus.Util because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/SerialConnection.class
skipping className=mdt.neuro.nexus.SerialConnection because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/DataFrameHeader$DataFrameSource.class
entryName = mdt/neuro/nexus/DataFrameHeader.class
skipping className=mdt.neuro.nexus.DataFrameHeader because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/CommandAccessor.class
skipping className=mdt.neuro.nexus.CommandAccessor because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/DataFramePayload.class
skipping className=mdt.neuro.nexus.DataFramePayload because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/ManualResetEvent.class
skipping className=mdt.neuro.nexus.ManualResetEvent because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/Crc.class
skipping className=mdt.neuro.nexus.Crc because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/ExecutionEngine.class
skipping className=mdt.neuro.nexus.ExecutionEngine because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/DataPacketAccessor.class
skipping className=mdt.neuro.nexus.DataPacketAccessor because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/ResponseCodes.class
skipping className=mdt.neuro.nexus.ResponseCodes because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/IDisposable.class
skipping className=mdt.neuro.nexus.IDisposable because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/Command.class
skipping className=mdt.neuro.nexus.Command because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/AutoResetEvent.class
skipping className=mdt.neuro.nexus.AutoResetEvent because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/DecFrequency.class
skipping className=mdt.neuro.nexus.commands.DecFrequency because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/CommandProvider.class
skipping className=mdt.neuro.nexus.commands.CommandProvider because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/CycleStim.class
skipping className=mdt.neuro.nexus.commands.CycleStim because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/SetNexusConfiguration.class
skipping className=mdt.neuro.nexus.commands.SetNexusConfiguration because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/GetNexusStatus.class
skipping className=mdt.neuro.nexus.commands.GetNexusStatus because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/GetInsInfo.class
skipping className=mdt.neuro.nexus.commands.GetInsInfo because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/IncPulseWidth.class
skipping className=mdt.neuro.nexus.commands.IncPulseWidth because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/TherapyOff.class
skipping className=mdt.neuro.nexus.commands.TherapyOff because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/CommandCodes.class
skipping className=mdt.neuro.nexus.commands.CommandCodes because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/PulseStim.class
skipping className=mdt.neuro.nexus.commands.PulseStim because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/CommandResponseCodes.class
skipping className=mdt.neuro.nexus.commands.CommandResponseCodes because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/StartSensing.class
skipping className=mdt.neuro.nexus.commands.StartSensing because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/IncAmplitude.class
skipping className=mdt.neuro.nexus.commands.IncAmplitude because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/StopSensing.class
skipping className=mdt.neuro.nexus.commands.StopSensing because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/GetRealtimeData.class
skipping className=mdt.neuro.nexus.commands.GetRealtimeData because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/StartRealTime.class
skipping className=mdt.neuro.nexus.commands.StartRealTime because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/StopRealTime.class
skipping className=mdt.neuro.nexus.commands.StopRealTime because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/SendTrigger.class
skipping className=mdt.neuro.nexus.commands.SendTrigger because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/DecPulseWidth.class
skipping className=mdt.neuro.nexus.commands.DecPulseWidth because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/DataStructureAccessor.class
skipping className=mdt.neuro.nexus.commands.DataStructureAccessor because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/IncFrequency.class
skipping className=mdt.neuro.nexus.commands.IncFrequency because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/RestoreClinicianSettings.class
skipping className=mdt.neuro.nexus.commands.RestoreClinicianSettings because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/SetActiveGroup.class
skipping className=mdt.neuro.nexus.commands.SetActiveGroup because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/TherapyOn.class
skipping className=mdt.neuro.nexus.commands.TherapyOn because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/ResetCycle.class
skipping className=mdt.neuro.nexus.commands.ResetCycle because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/commands/DecAmplitude.class
skipping className=mdt.neuro.nexus.commands.DecAmplitude because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/NexusState.class
skipping className=mdt.neuro.nexus.data.NexusState because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/DataPacketProvider.class
skipping className=mdt.neuro.nexus.data.DataPacketProvider because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/ChannelType.class
skipping className=mdt.neuro.nexus.data.ChannelType because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/NexusStatus.class
skipping className=mdt.neuro.nexus.data.NexusStatus because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/AmplitudeResolution.class
skipping className=mdt.neuro.nexus.data.AmplitudeResolution because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/DataStructureProvider.class
skipping className=mdt.neuro.nexus.data.DataStructureProvider because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/DataPacket.class
skipping className=mdt.neuro.nexus.data.DataPacket because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/SensingState.class
skipping className=mdt.neuro.nexus.data.SensingState because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/ProgramInfo.class
skipping className=mdt.neuro.nexus.data.ProgramInfo because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/InsInfo.class
skipping className=mdt.neuro.nexus.data.InsInfo because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/data/TherapyParameter.class
skipping className=mdt.neuro.nexus.data.TherapyParameter because it does not found in=[NexusTester]
entryName = mdt/neuro/nexus/support/NexusLogger.class
skipping className=mdt.neuro.nexus.support.NexusLogger because it does not found in=[NexusTester]
Checking classnames arguments
classname = NexusTester
url = file:/home/pi/Desktop/testNexus/NexusTest/bin/
c = class NexusTester
Finished checking classnames arguments
Classes found = 1
Exception in thread "main" java.lang.NoClassDefFoundError: mdt/neuro/nexus/ObservableConnection
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2570)
    at java.lang.Class.getDeclaredFields(Class.java:1903)
    at com.github.wshackle.java4cpp.J4CppMain.main(J4CppMain.java:1379)
Caused by: java.lang.ClassNotFoundException: mdt.neuro.nexus.ObservableConnection
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:798)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 4 more

**Comment by kenantufekci** [comment]
Same exact issue occurs after pulling and recompiling your changes for 1.2

The classes that it is looking for are in the nexus.jar, which is an external jar. In my main class NexusTester I use the classes in nexus.jar to create objects and call functions associated with those classes. It seems to keep looking at the main class instead of the external jar to find the classes needed.

**Comment by wshackle** [comment]
I have committed and pushed another change to address the issue.

Which explicitly adds the jar's from the environment variable CLASSPATH.

Running the jar apparantly overrides the classpath as set with -cp so it
needs to use the environment variable.

eg either

export CLASSPATH=.:jssc.jar:nexus.jar
java  -jar
/home/pi/Desktop/java4cpp/target/java4cpp-1.2-SNAPSHOT-jar-with-dependencies.jar
-j nexus.jar -j jssc.jar -c NexusTester -v

or use env to run it on one line

env CLASSPATH=.:jssc.jar:nexus.jar java -jar
/home/pi/Desktop/java4cpp/target/java4cpp-1.2-SNAPSHOT-jar-with-dependencies.jar
-j nexus.jar -j jssc.jar -c NexusTester -v

using the -j should also not be necessary

env CLASSPATH=.:jssc.jar:nexus.jar java -jar
/home/pi/Desktop/java4cpp/target/java4cpp-1.2-SNAPSHOT-jar-with-dependencies.jar
-c NexusTester -v

**Comment by wshackle** [comment]
looks like I lied earlier in that I committed but forgot to push

just pushed the change

**Comment by kenantufekci** [comment]
Thank you so much it works now! I will let you know if any other issues occur.
